/*
 * FormularioPrincipal.java
 *
 * Created on 26 de Setembro de 2008, 11:22
 */

package visao;

import visao.baixaestoque.FormularioBaixaEstoque;
import visao.produto.FormularioManutencaoProduto;
import visao.grupo.FormularioManutencaoGrupoProduto;

/**
 *
 * @author  Evandro
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /** Creates new form FormularioPrincipal */
    public FormularioPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuManutencao = new javax.swing.JMenu();
        itemMenuManutencaoProduto = new javax.swing.JMenuItem();
        itemMenuGrupoProduto = new javax.swing.JMenuItem();
        menuOperacoes = new javax.swing.JMenu();
        itemMenuBaixaEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manutenção de Produto e Estoque");
        getContentPane().setLayout(null);

        menuManutencao.setText("Tabelas");

        itemMenuManutencaoProduto.setText("Produto");
        itemMenuManutencaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuManutencaoProdutoActionPerformed(evt);
            }
        });
        menuManutencao.add(itemMenuManutencaoProduto);

        itemMenuGrupoProduto.setText("Grupo Produto");
        itemMenuGrupoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuGrupoProdutoActionPerformed(evt);
            }
        });
        menuManutencao.add(itemMenuGrupoProduto);

        jMenuBar1.add(menuManutencao);

        menuOperacoes.setText("Operações");

        itemMenuBaixaEstoque.setText("Baixa de Estoque");
        itemMenuBaixaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBaixaEstoqueActionPerformed(evt);
            }
        });
        menuOperacoes.add(itemMenuBaixaEstoque);

        jMenuBar1.add(menuOperacoes);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-380)/2, (screenSize.height-327)/2, 380, 327);
    }// </editor-fold>//GEN-END:initComponents

private void itemMenuManutencaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuManutencaoProdutoActionPerformed
    FormularioManutencaoProduto tela = new FormularioManutencaoProduto();
    tela.setVisible(true);
}//GEN-LAST:event_itemMenuManutencaoProdutoActionPerformed

private void itemMenuBaixaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBaixaEstoqueActionPerformed
    FormularioBaixaEstoque tela = new FormularioBaixaEstoque();
    tela.setVisible(true);
}//GEN-LAST:event_itemMenuBaixaEstoqueActionPerformed

private void itemMenuGrupoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGrupoProdutoActionPerformed
    FormularioManutencaoGrupoProduto tela = new FormularioManutencaoGrupoProduto();
    tela.setVisible(true);
}//GEN-LAST:event_itemMenuGrupoProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuBaixaEstoque;
    private javax.swing.JMenuItem itemMenuGrupoProduto;
    private javax.swing.JMenuItem itemMenuManutencaoProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuManutencao;
    private javax.swing.JMenu menuOperacoes;
    // End of variables declaration//GEN-END:variables

}
